config/routes.rb
Rails.application.routes.draw do

  resources :organization_sites
  resources :user_sites
  resources :sites
  resources :user_server_roles
  resources :user_roles
  resources :roles
  resources :organizations
  resources :users
  resources :system_roles
  resources :projects

  root 'welcome#index'

  get 'login' => 'auth#signin'
  post 'login' => 'auth#signin'

  get 'signup' => 'auth#signup'
  post 'signup' => 'auth#signup'

  get 'logout' => 'auth#signout'
  post 'logout' => 'auth#signout'

  get 'admin' => 'admin#index'

  get 'gallery' => 'gallery#index'

  get 'manage' => 'manage#index'

  get 'account' => 'account#index'

  get 'capture' => 'capture#index'

end

app/models/organization.rb
class Organization < ActiveRecord::Base
  has_many :roles
  has_many :projects
  has_many :organization_sites
end

app/models/organization_site.rb
class OrganizationSite < ActiveRecord::Base
  belongs_to :organization
  has_one :site
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_one :organization
end

app/models/role.rb
class Role < ActiveRecord::Base
  belongs_to :organization
  has_and_belongs_to_many :user
end

app/models/site.rb
class Site < ActiveRecord::Base
end

app/models/system_role.rb
class SystemRole < ActiveRecord::Base
  has_one :server_role
  has_and_belongs_to_many :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  has_many :user_roles
  has_and_belongs_to_many :system_roles
  has_and_belongs_to_many :roles
  has_many :user_sites

  validates :password, length: { minimum: 6, maximum: 72 }

  validates_uniqueness_of :name
  validates :name, length: { minimum: 6, maximum: 24 }

  validates_uniqueness_of :email
  validates :email, :format => /.+@.+\..+/, length: { maximum: 48 }

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/models/user_role.rb
class UserRole < ActiveRecord::Base
  has_one :role
  belongs_to :user
end

app/models/user_site.rb
class UserSite < ActiveRecord::Base
  belongs_to :user
  has_one :site
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController

  # TODO - control admin access based on system roles
  before_filter :authorize_admin


  protected

  def authorize_admin
    user = User.find_by_id(session[:user_id])
    user.system_roles.each do |sr|
      if  "admin" == sr.name
        return
      end
    end

    redirect_to "/"
  end

end

app/controllers/auth_controller.rb
class AuthController < ApplicationController

  skip_before_action :authorize, :only => [:signin, :signup]

  def signin
    # TODO - check if logged in - can't sign in until you're logged out
    session[:user_id] = nil
    if request.post?
      user = User.find_by_email(params[:email])
      if user && user.authenticate(params[:password])
        session[:user_id] = user.id
        redirect_to "/" # TODO - redirect to where they came from
      else
        flash.now[:danger] = "Invalid email or password"
      end
    end
  end

  def signup
    # TODO - check if logged in. can't sign up until you log out

    if request.post?
      begin
        user = User.new(name: params[:name], email: params[:email], 
                        password: params[:password], 
                        password_confirmation: params[:password_confirmation])
        user.save!
      rescue Exception => e
        flash.now[:danger] = e # HACKME - clean this up
      end
      if user && user.id
        session[:user_id] = user.id
        redirect_to "/" # TODO - redirect to where they came from
      else
        flash.now[:danger] = "unable to create user"
      end
    end
    # TODO - create new account
  end

  def signout
    if request.post?
      if params[:logout_confirmed]
        session[:user_id] = nil
        redirect_to "/" 
      end
    end
  end


end

app/controllers/login_controller.rb
class LoginController < ApplicationController
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  before_action :set_organization, only: [:show, :edit, :update, :destroy]

  # GET /organizations
  # GET /organizations.json
  def index
    @organizations = Organization.all
  end

  # GET /organizations/1
  # GET /organizations/1.json
  def show
  end

  # GET /organizations/new
  def new
    @organization = Organization.new
  end

  # GET /organizations/1/edit
  def edit
  end

  # POST /organizations
  # POST /organizations.json
  def create
    @organization = Organization.new(organization_params)

    respond_to do |format|
      if @organization.save
        format.html { redirect_to @organization, notice: 'Organization was successfully created.' }
        format.json { render :show, status: :created, location: @organization }
      else
        format.html { render :new }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /organizations/1
  # PATCH/PUT /organizations/1.json
  def update
    respond_to do |format|
      if @organization.update(organization_params)
        format.html { redirect_to @organization, notice: 'Organization was successfully updated.' }
        format.json { render :show, status: :ok, location: @organization }
      else
        format.html { render :edit }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /organizations/1
  # DELETE /organizations/1.json
  def destroy
    @organization.destroy
    respond_to do |format|
      format.html { redirect_to organizations_url, notice: 'Organization was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_organization
      @organization = Organization.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def organization_params
      params.require(:organization).permit(:name, :business_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/capture_helper.rb
module CaptureHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/helpers/user_roles_helper.rb
module UserRolesHelper
end

app/helpers/user_sites_helper.rb
module UserSitesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/organizations/_form.html.erb
<%= form_for(@organization) do |f| %>
  <% if @organization.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@organization.errors.count, "error") %> prohibited this organization from being saved:</h2>

      <ul>
      <% @organization.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :business_id %><br>
    <%= f.text_field :business_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/organizations/edit.html.erb
<h1>Editing Organization</h1>

<%= render 'form' %>

<%= link_to 'Show', @organization %> |
<%= link_to 'Back', organizations_path %>

app/views/organizations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Organizations</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Business</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @organizations.each do |organization| %>
      <tr>
        <td><%= organization.name %></td>
        <td><%= organization.business_id %></td>
        <td><%= link_to 'Show', organization %></td>
        <td><%= link_to 'Edit', edit_organization_path(organization) %></td>
        <td><%= link_to 'Destroy', organization, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Organization', new_organization_path %>

app/views/organizations/new.html.erb
<h1>New Organization</h1>

<%= render 'form' %>

<%= link_to 'Back', organizations_path %>

app/views/organizations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @organization.name %>
</p>

<p>
  <strong>Business:</strong>
  <%= @organization.business_id %>
</p>

<p>
  <strong>Sites:</strong>
  <%= @organization.organization_sites.length %>
  <%= @organization.organization_sites %>
</p>

<p>
  <strong>Projects:</strong>
  <%= @organization.projects.length %>
  <%= @organization.projects %>
</p>

<p>
  <strong>Roles:</strong>
  <%= @organization.roles.length %>
  <%= @organization.roles %>
</p>



<%= link_to 'Edit', edit_organization_path(@organization) %> |
<%= link_to 'Back', organizations_path %>