config/routes.rb
Rails.application.routes.draw do

  resources :organization_sites
  resources :user_sites
  resources :sites
  resources :user_server_roles
  resources :user_roles
  resources :roles
  resources :organizations
  resources :users
  resources :system_roles
  resources :projects

  root 'welcome#index'

  get 'login' => 'auth#signin'
  post 'login' => 'auth#signin'

  get 'signup' => 'auth#signup'
  post 'signup' => 'auth#signup'

  get 'logout' => 'auth#signout'
  post 'logout' => 'auth#signout'

  get 'admin' => 'admin#index'

  get 'gallery' => 'gallery#index'

  get 'manage' => 'manage#index'

  get 'account' => 'account#index'

  get 'capture' => 'capture#index'

end

app/models/organization.rb
class Organization < ActiveRecord::Base
  has_many :roles
  has_many :projects
  has_many :organization_sites
end

app/models/organization_site.rb
class OrganizationSite < ActiveRecord::Base
  belongs_to :organization
  has_one :site
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_one :organization
end

app/models/role.rb
class Role < ActiveRecord::Base
  belongs_to :organization
  has_and_belongs_to_many :user
end

app/models/site.rb
class Site < ActiveRecord::Base
end

app/models/system_role.rb
class SystemRole < ActiveRecord::Base
  has_one :server_role
  has_and_belongs_to_many :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  has_many :user_roles
  has_and_belongs_to_many :system_roles
  has_and_belongs_to_many :roles
  has_many :user_sites

  validates :password, length: { minimum: 6, maximum: 72 }

  validates_uniqueness_of :name
  validates :name, length: { minimum: 6, maximum: 24 }

  validates_uniqueness_of :email
  validates :email, :format => /.+@.+\..+/, length: { maximum: 48 }

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/models/user_role.rb
class UserRole < ActiveRecord::Base
  has_one :role
  belongs_to :user
end

app/models/user_site.rb
class UserSite < ActiveRecord::Base
  belongs_to :user
  has_one :site
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController

  # TODO - control admin access based on system roles
  before_filter :authorize_admin


  protected

  def authorize_admin
    user = User.find_by_id(session[:user_id])
    user.system_roles.each do |sr|
      if  "admin" == sr.name
        return
      end
    end

    redirect_to "/"
  end

end

app/controllers/auth_controller.rb
class AuthController < ApplicationController

  skip_before_action :authorize, :only => [:signin, :signup]

  def signin
    # TODO - check if logged in - can't sign in until you're logged out
    session[:user_id] = nil
    if request.post?
      user = User.find_by_email(params[:email])
      if user && user.authenticate(params[:password])
        session[:user_id] = user.id
        redirect_to "/" # TODO - redirect to where they came from
      else
        flash.now[:danger] = "Invalid email or password"
      end
    end
  end

  def signup
    # TODO - check if logged in. can't sign up until you log out

    if request.post?
      begin
        user = User.new(name: params[:name], email: params[:email], 
                        password: params[:password], 
                        password_confirmation: params[:password_confirmation])
        user.save!
      rescue Exception => e
        flash.now[:danger] = e # HACKME - clean this up
      end
      if user && user.id
        session[:user_id] = user.id
        redirect_to "/" # TODO - redirect to where they came from
      else
        flash.now[:danger] = "unable to create user"
      end
    end
    # TODO - create new account
  end

  def signout
    if request.post?
      if params[:logout_confirmed]
        session[:user_id] = nil
        redirect_to "/" 
      end
    end
  end


end

app/controllers/login_controller.rb
class LoginController < ApplicationController
end

app/controllers/organization_sites_controller.rb
class OrganizationSitesController < ApplicationController
  before_action :set_organization_site, only: [:show, :edit, :update, :destroy]

  # GET /organization_sites
  # GET /organization_sites.json
  def index
    @organization_sites = OrganizationSite.all
  end

  # GET /organization_sites/1
  # GET /organization_sites/1.json
  def show
  end

  # GET /organization_sites/new
  def new
    @organization_site = OrganizationSite.new
  end

  # GET /organization_sites/1/edit
  def edit
  end

  # POST /organization_sites
  # POST /organization_sites.json
  def create
    @organization_site = OrganizationSite.new(organization_site_params)

    respond_to do |format|
      if @organization_site.save
        format.html { redirect_to @organization_site, notice: 'Organization site was successfully created.' }
        format.json { render :show, status: :created, location: @organization_site }
      else
        format.html { render :new }
        format.json { render json: @organization_site.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /organization_sites/1
  # PATCH/PUT /organization_sites/1.json
  def update
    respond_to do |format|
      if @organization_site.update(organization_site_params)
        format.html { redirect_to @organization_site, notice: 'Organization site was successfully updated.' }
        format.json { render :show, status: :ok, location: @organization_site }
      else
        format.html { render :edit }
        format.json { render json: @organization_site.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /organization_sites/1
  # DELETE /organization_sites/1.json
  def destroy
    @organization_site.destroy
    respond_to do |format|
      format.html { redirect_to organization_sites_url, notice: 'Organization site was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_organization_site
      @organization_site = OrganizationSite.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def organization_site_params
      params.require(:organization_site).permit(:organization_id, :site_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/capture_helper.rb
module CaptureHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/organization_sites_helper.rb
module OrganizationSitesHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/helpers/user_roles_helper.rb
module UserRolesHelper
end

app/helpers/user_sites_helper.rb
module UserSitesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/organization_sites/_form.html.erb
<%= form_for(@organization_site) do |f| %>
  <% if @organization_site.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@organization_site.errors.count, "error") %> prohibited this organization_site from being saved:</h2>

      <ul>
      <% @organization_site.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :organization_id %><br>
    <%= f.number_field :organization_id %>
  </div>
  <div class="field">
    <%= f.label :site_id %><br>
    <%= f.number_field :site_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/organization_sites/edit.html.erb
<h1>Editing Organization Site</h1>

<%= render 'form' %>

<%= link_to 'Show', @organization_site %> |
<%= link_to 'Back', organization_sites_path %>

app/views/organization_sites/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Organization Sites</h1>

<table>
  <thead>
    <tr>
      <th>Organization</th>
      <th>Site</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @organization_sites.each do |organization_site| %>
      <tr>
        <td><%= organization_site.organization_id %></td>
        <td><%= organization_site.site_id %></td>
        <td><%= link_to 'Show', organization_site %></td>
        <td><%= link_to 'Edit', edit_organization_site_path(organization_site) %></td>
        <td><%= link_to 'Destroy', organization_site, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Organization site', new_organization_site_path %>

app/views/organization_sites/new.html.erb
<h1>New Organization Site</h1>

<%= render 'form' %>

<%= link_to 'Back', organization_sites_path %>

app/views/organization_sites/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Organization:</strong>
  <%= @organization_site.organization_id %>
</p>

<p>
  <strong>Site:</strong>
  <%= @organization_site.site_id %>
</p>

<%= link_to 'Edit', edit_organization_site_path(@organization_site) %> |
<%= link_to 'Back', organization_sites_path %>